### ISSUE TITLE
♻️ refactor: User 부분 리팩토링

### ISSUE THREAD

**Issue by Bxxrxtop** [SMUMC-7th/Team-A-BE#8]
# Title
User 부분 리팩토링

- 자세한 개요 작성
- User 엔티티 authType추가
- 닉네임 변경 부분 수정
- 소셜로그인 api 구현

# TODO

- [x] User 엔티티 authType추가
- [x] 닉네임 변경 부분 수정
- [x] 소셜 로그인 api 구현

# etc
